/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { UserDTO } from './userDTO';

export interface ClassDTO { 
    id?: number;
    subject?: Array<number>;
    districts?: string;
    price?: string;
    numberSessions?: string;
    timeTeach?: string;
    information?: string;
    request?: string;
    describes?: string;
    userDTO?: UserDTO;
    districtDTO?: number;
    levelSchool?: number;
    teachClass?: Array<number>;
    city?: number;
}