/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { District } from './district';
import { Subject } from './subject';

export interface ModelClass { 
    id?: number;
    districts?: string;
    price?: string;
    numberSessions?: string;
    timeTeach?: string;
    information?: string;
    request?: string;
    describes?: string;
    district?: District;
    subjects?: Array<Subject>;
}