/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Majored } from './majored';
import { Subject } from './subject';
import { TimeTeach } from './timeTeach';

export interface User { 
    id?: number;
    fullName?: string;
    email?: string;
    password?: string;
    sex?: string;
    address?: string;
    birthDay?: Date;
    phone?: string;
    voice?: string;
    education?: string;
    mature?: string;
    university?: string;
    yearOfAdmission?: string;
    graduationYear?: string;
    request?: string;
    subjects?: Array<Subject>;
    majored?: Majored;
    timeTeaches?: Array<TimeTeach>;
    cmnd?: string;
}