/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ClassDTO } from './classDTO';

export interface UserDTO { 
    fullName?: string;
    email?: string;
    password?: string;
    sex?: string;
    address?: string;
    birthDay?: Date;
    cmnd?: string;
    phone?: string;
    voice?: string;
    education?: string;
    mature?: string;
    university?: string;
    yearOfAdmission?: string;
    graduationYear?: string;
    districtDTOS?: Array<string>;
    classDTOS?: Array<ClassDTO>;
    subjectDTOS?: Array<string>;
    majoredDTO?: string;
    teachClassDTOS?: Array<string>;
    cityDTO?: string;
    timeTeachDTO?: Array<string>;
    request?: string;
}